# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mover_moverinfo',
            old_name='driver_name',
            new_name='name',
        ),
    ]
